# Useful guides:
# https://www.sphinx-doc.org/en/master/tutorial/deploying.html
# https://marcomadera.com/blog/github-pages (spanish)
# https://coderefinery.github.io/documentation/gh_workflow/

name: Deploy docs to GH Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Build pages
      run: make html

    - name: Deploy to build branch
      uses: peaceiris/actions-gh-pages@v3.9.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: _build/html/
